on:
  workflow_call:
    inputs:
      id:
        type: string
      environment:
        type: string

jobs:
  something:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "abc"
      - run: echo inputs.id
