on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
  
jobs:
  env:
    strategy:
      matrix:
        env: [ 'standby', 'staging' ]
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    outputs:
      test: ${{ vars.ACCOUNT_ID }}
      ${{ matrix.environment }}: test
    steps:
      - run: ':'
    
  print:
    needs: env
    strategy:
      matrix:
        env: [ 'standby', 'staging' ]
    uses: ./.github/workflows/reusable.yaml
    with:
      environment: ${{ inputs.environment }}
      id: ${{ needs.env.outputs.test }}
