on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
  
jobs:
  env:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      test: ${{ vars.ACCOUNT_ID }}
    steps:
      - run: ':'
    
  print:
    needs: env
    uses: ./.github/workflows/reusable.yaml
    with:
      environment: ${{ inputs.environment }}
      id: ${{ needs.env.outputs.test }}
